version: "3.4"

services:
  app01-inmemory:
    build:
      dockerfile: StudentEnrollment01.InMemory/Dockerfile
      context: .
    container_name: app01-inmemory
  
  student-enrollment-esdb:
    image: eventstore/eventstore:24.2.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    networks:
      - student-enrollment-esdb-net
networks:
  student-enrollment-esdb-net:
    driver: bridge